#!/bin/bash
#
# Run all PHP commands through a docker container
#
VER=${PHPVERSION:-7.0-cli}
ARGS="-a"
if [ $# -gt 0 ]; then
    ARGS="$@"
fi
docker run \
    -it \
    --rm \
    -v $(pwd):/code \
    -w /code php:$VER php $ARGS
