#!/bin/bash
#
# Run all PHP commands through a docker container
#
VER=${PHPVERSION:-7.0-cli}
ARGS="-a"
if [ $# -gt 0 ]; then
    ARGS="$@"
fi
tty=
tty -s && tty=--tty
docker run \
    $tty \
    --interactive \
    --rm \
    -v "$(pwd)":/code \
    -v /usr/local/bin/phpmd:/usr/local/bin/phpmd \
    -v /usr/local/bin/phpcs:/usr/local/bin/phpcs \
    -v /usr/local/bin/phpcbf:/usr/local/bin/phpcbf \
    -w /code php:$VER php $ARGS
