#!/bin/bash
#
# Run all PHP commands through a docker container
#
VER=${PHPVERSION:-7.4-cli}
ARGS="-a"
PORT="$1"
tty=
tty -s && tty=--tty
docker run \
    $tty \
    --interactive \
    --rm \
    -p "$PORT:$PORT" \
    -v "$(pwd)":/code \
    -w /code php:$VER php -S 0.0.0.0:$PORT
